we should define our own exception, or accept this case
